---
dependency:
  name: galaxy
driver:
  name: delegated
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
platforms:
  - name: molecule-test
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    KUBECONFIG: /home/austin/.kube/config-molecule-test
    K8S_AUTH_KUBECONFIG: /home/austin/.kube/config-molecule-test
