apiVersion: v1
kind: Pod
metadata:
  name: inspect-pvc-pod
spec:
  containers:
  - name: inspect-pvc-container
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        #!/bin/sh
        set -eux

        # EFS_PERSIST_MNT is the mount point for the PVC
        EFS_PERSIST_MNT="/mnt/efs-persist"
        EFS_HOME="$EFS_PERSIST_MNT/home"

        # Generate the size report
        du -sh $EFS_HOME/* | awk '{print $1, $2}' > $EFS_HOME/size_report.txt

        # Display the size report
        cat "$EFS_HOME/size_report.txt"
        
        # Keep the container running
        sleep 3600
    volumeMounts:
    - name: efs-storage
      mountPath: /mnt/efs-persist
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-persist

