---
apiVersion: v1
kind: Pod
metadata:
  name: inspect-pvc-pod
spec:
  containers:
    - name: inspect-pvc-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: efs-storage
          mountPath: /mnt/efs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-persist
